//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IHOWebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class FieldNote
    {
        public int Id { get; set; }
        public string ProfessorName { get; set; }
        public string ImageSrc { get; set; }
        public string Bio { get; set; }
        public string MailAddress { get; set; }
    }
}
